window.SEGFLOW_SALES_NURTURE_DATA = {
  version: 1,
  title: "SegFlow — Sales Nurture (после первой встречи)",
  description:
    "Лёгкая nurture‑последовательность для лидов, которые не купили после 1‑й встречи: 5 касаний за ~2 месяца. Каждый этап = артефакт (короткий отчёт) + готовое сообщение для отправки.",
  lead_placeholders: {
    company: "",
    product: "",
    geo: "",
    industry: "",
    competitors_shortlist: "",
  },
  demo_lead: {
    company: "FitHome",
    product: "Fitness app: домашние тренировки + персональные планы + трекинг прогресса (subscription)",
    geo: "US",
    industry: "B2C Fitness / Wellness (mobile app)",
    competitors_shortlist: ["Nike Training Club", "Apple Fitness+", "Peloton", "Freeletics", "FitOn", "Centr", "Sweat"].join("\n"),
  },
  touches: [
    {
      id: "T01",
      day: 2,
      title: "Источники рынка + первые сигналы (corpus profile)",
      goal: "Показать, на каких источниках строится анализ, и какие сегменты/контексты уже видны в материалах.",
      report_path: "templates/t01_report_value_map.md",
      telegram_path: "templates/t01_telegram.md",
      demo_report_path: "demo/t01_report_value_map_demo.md",
      demo_telegram_path: "demo/t01_telegram_demo.md",
      dependency_elements: ["project_input", "source_*", "analysis_sources_corpus_profile", "catalogs"],
      notes: "Этап 1: профиль корпуса источников (pie mix, свежесть/гео/доверие) + первые рыночные сигналы и shortlist сильных PDF‑источников.",
    },
    {
      id: "T02",
      day: 10,
      title: "Карта спроса: 21 сегмент × 52 потребности",
      goal: "Показать структуру спроса и почему стратегия — это связки Segment → Need → Functions, а не “один месседж на всех”.",
      report_path: "templates/t02_report_market_map.md",
      telegram_path: "templates/t02_telegram.md",
      demo_report_path: "demo/t02_report_market_map_demo.md",
      demo_telegram_path: "demo/t02_telegram_market_map_demo.md",
      dependency_elements: ["catalogs", "analysis_segment_need_importance", "analysis_need_feature_coverage_kano", "analysis_benchmark_segment_size"],
      notes: "Этап 2: полный список сегментов/потребностей (scroll) + матрица Segment×Need + сигналы конкурентов по потребностям + примеры Need→Functions/креативов.",
    },
    {
      id: "T03",
      day: 24,
      title: "Конкуренты: функции + позиционирование",
      goal: "Показать, какие функции реально реализованы у конкурентов и как они позиционируются по сегментам/потребностям/функциям (mentions).",
      report_path: "templates/t03_report_competitors_heatmap.md",
      telegram_path: "templates/t03_telegram.md",
      demo_report_path: "demo/t03_report_competitors_heatmap_demo.md",
      demo_telegram_path: "demo/t03_telegram_competitors_demo.md",
      dependency_elements: ["competitors", "analysis_competitor_target_segments", "analysis_competitor_positioning", "analysis_competitor_contradictions", "analysis_competitor_feature_mentions"],
      notes: "Этап 3: карта “competitor→functions” + маппинг на сегменты/потребности + позиционирование в коммуникации (segments/needs/functions mentions).",
    },
    {
      id: "T04",
      day: 38,
      title: "GTM‑стратегия (быстрый расчёт): связки + funnel + sales pack",
      goal: "Дать рассчитанную (teaser) стратегию на короткой выборке: 3×3×3×3, с готовыми материалами для теста.",
      report_path: "templates/t04_report_gtm_strategy.md",
      telegram_path: "templates/t04_telegram.md",
      demo_report_path: "demo/t04_report_gtm_strategy_demo.md",
      demo_telegram_path: "demo/t04_telegram_gtm_strategy_demo.md",
      dependency_elements: ["gtm_strategy", "unit_econ_math", "swot5", "analysis_sales_funnel_blueprint", "sales_funnel_playbook"],
      notes: "Этап 4: быстрый расчёт GTM‑портфеля на короткой выборке (фокус на 3 сегмента/потребности/фичи/канала) + краткий sales funnel + базовый пакет sales‑материалов.",
    },
    {
      id: "T05",
      day: 56,
      title: "Мониторинг конкурентов: что изменилось → обновление стратегии и sales‑материалов",
      goal: "Показать изменения рынка и дать обновлённый пакет: что менять в связках, funnel и сообщениях.",
      report_path: "templates/t05_report_strategy_update.md",
      telegram_path: "templates/t05_telegram.md",
      demo_report_path: "demo/t05_report_strategy_update_demo.md",
      demo_telegram_path: "demo/t05_telegram_strategy_update_demo.md",
      dependency_elements: ["analysis_competitor_positioning", "analysis_competitor_feature_mentions", "analysis_competitor_contradictions", "gtm_strategy", "sales_funnel_playbook"],
      notes: "Этап 5: самое длинное ожидание — мониторинг изменений у конкурентов и пересборка GTM (включая обновлённые sales‑материалы).",
    },
  ],
};
